### ISSUE TITLE
Is there any update for Laravel 5.0

### ISSUE THREAD

**Issue by austinkregel** [eubby06/forum#3]
Hello, I'm curious as to see if there is a L5 version of this repo. If not, is there some other forum package that is compatible with L5?

**Comment by eubby06** [comment]
> Hello, I'm curious as to see if there is a L5 version of this repo. If not, is there some other forum package that is compatible with L5?

wow this was 6 years ago, I'm just sorry for not answering :(

**Comment by austinkregel** [comment]
:joy: No worries! I completely forgot this was open :joy:
